Server:
  port: 8087

spring:
  application:
    name: users-service
#  eureka:
#    client:
#      enabled: true
#      service-url:
#        defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/usersdb
#      username: admin
#      password: admin
#      database: tp_pi
#      port: 27017
#      host: mongodb #localhost
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.H2Dialect
      open-in-view: false
    h2:
      console:
        enabled: true
        path: /h2-console
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/My-Realm
        registration:
          keycloak:
            client-id: spring-gateway-client
            client-secret: 3RhEF8pqKTANrQ6BhfxaYVmcjTXsDK0u
            scope: openid
            redirect_uri: http://localhost:8087
            realm: My-Realm
            serverUrl: http://localhost:8080


app:
  cors:
    allowed-origins: http://localhost:3000

dh:
  keycloakInternal:
    realm: My-Realm
    serverUrl: http://localhost:8080
    clientId: internal
    clientSecret: LEI9chHXb3ZPEBb0v4NpLgRibkHGElRw
