Server:
  port: 8087

spring:
  application:
    name: users-service
#  eureka:
#    client:
#      enabled: true
#      service-url:
#        defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  data:
    mongodb:
      username: usrmongo
      password: pwdmongo
      database: usermongo
      port: 27020
      host: localhost

  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/My-Realm
        registration:
          keycloak:
            client-id: spring-gateway-client
            client-secret: 3RhEF8pqKTANrQ6BhfxaYVmcjTXsDK0u
            scope: openid
            redirect_uri: http://localhost:8087
            realm: My-Realm
            serverUrl: http://localhost:8080


app:
  cors:
    allowed-origins: http://localhost:3000

dh:
  keycloakInternal:
    realm: My-Realm
    serverUrl: http://localhost:8080
    clientId: internal
    clientSecret: LEI9chHXb3ZPEBb0v4NpLgRibkHGElRw


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
