server:
  port: 8087

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/digitalmedia
            jwk-set-uri: http://localhost:8080/realms/digitalmedia/protocol/openid-connect/certs
        registration:
          keycloack:
            provider: keycloak
            client-id: microservicios
            client-secret: EfTV7vcTXzMbZmKAk3B6gnJNnZ02Mvxd
            redirect-uri: http://localhost:8087

  application:
    name: users-service

  data:
    mongodb:
      username: usrmongo
      password: pwdmongo
      database: usermongo
      port: 27020
      host: localhost
  main:
    allow-circular-references: true

app:
  cors:
    allowed-origins: http://localhost:3000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



#springdoc:
#  show-actuator: true
#  swagger-ui:
#    groups-order: DESC
#    disable-swagger-default-url: true
#management:
#  endpoints:
#    web:
#      exposure.include: beans, env, health, info, metrics, mappings
#  endpoint:
#    health:
#      show-details: always
