eureka:
  client:
    enabled: false

server:
  port: 8086

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true
management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

app:
  realm: digitalmedia
  cors:
    allowed-origins: http://localhost:3000

spring:
  application:
    name: users-service
  data:
    mongodb:
      host: localhost
      port: 27017
      password: admin
      username: root
      authentication-database: admin
      database: moviesdb
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/digitalmedia
        registration:
          users-service:
            client-id: microservicios
            client-secret: uxsP0mGqKh5bjFj2PUQ9qTL7ZVO8FOSN # client-secret Keycloak Isabela
            redirect-uri: http://localhost:8086/login/oauth2/code/keycloak
