server:
  port: 8086

spring:
  application:
    name: ms-bill

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/digitalmedia
            jwk-set-uri: http://localhost:8080/realms/digitalmedia/protocol/openid-connect/certs
        registration:
          ms-bill:
            provider: keycloak
            client-id: internal
            client-secret: Ml0VzE8xN2cPNIKmHVO6i7ncxkrS4pav
            redirect-uri: http://localhost:8086/login/oauth2/keycloak

  data:
    mongodb:
      username: usrmongo
      password: pwdmongo
      database: billmongo
      port: 27019
      host: localhost

