spring:
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8082/realms/digitalmedia
        registration:
          api-gateway-service:
            provider: keycloak-provider
            client-id: api-gateway-client
            client-secret: UW5WIVaBtuRw0z9KaiS3cgCWDippzdqX
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:9090/login/oauth2/code/keycloak'

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: api-movies
          uri: "http://localhost:8085/movies"
          predicates:
            - Path= /movies
        - id: users-service
          uri: "http://localhost:8086/"
          predicates:
            - Path= /user
#        - id: api-facturacion
#          uri: # http://localhost: puerto del proyecto
#          predicates:
#            - Path= / #endpoint api-facturación (?)

server:
  port: 9090