server:
  port: 8085

spring:
  application:
    name: movies-service

#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/digitalmedia
#            jwk-set-uri: http://localhost:8080/realms/digitalhouse/protocol/openid-connect/certs
#        registration:
#          keycloack:
#            provider: keycloak
#            client-id: microservicios
#            client-secret: EfTV7vcTXzMbZmKAk3B6gnJNnZ02Mvxd
#            redirect-uri: http://localhost:8085


  data:
    mongodb:
      username: usrmongo
      password: pwdmongo
      database: moviesmongo
      port: 27018
      host: localhost
  main:
    allow-circular-references: true

app:
  cors:
    allowed-origins: http://localhost:3000


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
